openapi: 3.0.3
info:
  version: 1.0.0
  title: Budget manager application
servers:
  - url: http://wallet.com
tags:
  - Currency
  - Transaction
  - Account
paths:
  /currency:
    get:
      tags:
        - Currency
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Currencys"
    post:
      tags:
        - Currency
      description: Create or update Currency type
      operationId: crupdateCurrency
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Currencys"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Currencys"

  /transaction:
    get:
      tags:
        - Transaction
      summary: Get all Transaction
      description: The returned Transaction are ordered by date.
      operationId: getTransaction
      responses:
        200:
          description: successfully returned
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transactions'
    put:
      summary: Create or update Transaction
      operationId: crupdateTransaction
      tags:
        - Transaction
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Transactions'
      responses:
        200:
          description: The list of created or updated currency
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transactions'
  /account:
    get:
      tags:
        - Account
      summary: Get all accounts
      description: The returned books are ordered by name.
      operationId: getAccounts
      responses:
        200:
          description: successfully returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Accounts'

    put:
      summary: Create or update accounts
      operationId: crupdateAccounts
      tags:
        - Account
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Accounts'
      responses:
        200:
          description: The list of created or updated accounts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Accounts'

components:
  schemas:
    Currencys:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string

    Transactions:
      type: object
      properties:
        id:
          type : string
        value:
          type: string
        description:
          type : string
        id_acount:
          type: string
        transaction_date :
          type: string
          format: date


    Accounts:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        id_currency:
          type: string